People
Rafal-1999/movies-browser-react pull request #2
Opened 2024-07-03 19:43 UTC by Rafal-1999

Pierwsze zmiany.

2024-07-03 19:48 UTC, adim2222 requested changes

2024-07-03 19:48 UTC, adim2222 commented on src/common/PersonCard/index.js
> +const PersonCard = ({ title, role }) => (
Tutaj jeszcze nie ma obrazu osoby

2024-07-04 19:53 UTC, Rafal-1999 commented on src/common/PersonCard/index.js
> +const PersonCard = ({ title, role }) => (
Dodałem obrazek.

2024-07-04 20:24 UTC, adim2222 approved these changes
działa

2024-07-04 20:25 UTC, merged