PersonCardFull
Rafal-1999/movies-browser-react pull request #25
Opened 2024-07-30 20:33 UTC by DawidGaski

created PersonCardFull component

2024-08-01 21:24 UTC, DawidGaski commented
please check my hooks and Api in files. I'm not sure API in ` usePeopleData ` (why discovery)

2024-08-02 12:49 UTC, adim2222 requested changes

2024-08-02 12:49 UTC, adim2222 commented on src/common/PersonCardFull/index.js
Karta pobiera dane, ale wyświetla się bez tła karty (Container powinno mieć bg white)

2024-08-02 12:49 UTC, adim2222 commented on src/peopleSlice.js
Dobrze że myślisz o zrobieniu osobnego slicea do strony people

2024-08-02 12:49 UTC, adim2222 commented on src/usePeopeDataById.js
Wydaje mi się że nie powinniśmy myśleć o pobieraniu danych w branchu PersonCardFull. zrób tylko style karty. Danymi zajmiemy się w stronie people.

2024-08-02 21:00 UTC, DawidGaski commented on src/common/PersonCardFull/index.js
Rzeczywiście, tło powinno być białe

2024-08-02 21:06 UTC, DawidGaski commented on src/usePeopeDataById.js
W porządku jeśli będzie taka potrzeba stworzymy do tego osobną gałąź, lub zmienimy nazwę i zakres obecnej.

2024-08-04 23:01 UTC, adim2222 approved these changes
Po dalszym omwieniu brancha wszystko dobrze.

2024-08-05 09:12 UTC, merged